
push-remote = "origin"
tag-name = "{{version}}"
publish = false

pre-release-replacements = [
  {file="CHANGELOG.md", search="# Unreleased", replace="# Unreleased\n\n# {{version}} - {{date}}"},
  {file="nix/package.nix", search="version = .*", replace="version = \"{{version}}\";"},
  {file="HomebrewFormula/dispatch.rb", search="version .*", replace="version \"{{version}}\""},
  {file="HomebrewFormula/dispatch.rb", search="sha256 .*", replace="sha256 \"replaced by CI on release of {{version}}\""},
  {file="HomebrewFormula/dispatch.rb", search="tags/[0-9.]+", replace="tags/{{version}}."},
]

